ClemsonRSRG/RESOLVE

src/main/java/edu/clemson/cs/r2jt/utilities/HardCoded.java
Changed the type value of SSET to SET to CLS. This will allow Murali's example for 828 to work. This is a temporary fix and will be expected to be changed at at future date.
=> changed the definition of sset

src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/CongruenceClassProver.java
CCProve shouldn't create an output file if we are invoking from the WebIDE
=> No proof file when running from WebIDE

src/main/java/edu/clemson/cs/r2jt/absyn/AssumeStmt.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/AssertiveCode.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java
The assume statements are now divided into stipulate statements (Even after substitution, these assumes don't go away!) and regular assume statements. The VC Generator only gets rid of givens that are regular assume statements and keeps the stipulate ones.
=> Implementation for Stipulate Assume Statements

src/main/java/edu/clemson/cs/r2jt/absyn/AssumeStmt.java, src/main/java/edu/clemson/cs/r2jt/misc/HardCoded.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java
1) Undo the previous pull request. The work space is not up to date, so the new compiler would not work at all.
2) Fix an instance where the if location is null.
3) If we encounter an infix expression inside the assume statement during simplification and a new AssumeStmt is created from the left/right expressions, we need to copy the original stipulate flag.
=> More vcgen fix

src/main/java/edu/clemson/cs/r2jt/absyn/MemoryStmt.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/AssertiveCode.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/OutputVCs.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/Utilities.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/VerificationStatement.java
The VC generator now has a new feature: Generation of Parsimonious VCs. Here are the steps performed by the VC generator:
1. During the Assume Rule, the processing assume statement and the final confirm statements that contain conjuncts are split into individual Exp and stored in a list object.
2. Using the list of assume and confirms, we first attempt to apply the simplification step. In order for the VC generator to simplify an assume expression, it must be an equals expression that contains either a replaceable left-hand side or right-hand side. A replaceable expression is defined as either a VarExp or DotExp containing a VarExp as the final segment. There is an exception: We do not replace VC generator generated expressions with variables such as ?*P_val or ?*Cum_Dur. These …
=> Parsimonious VCs

src/main/java/edu/clemson/cs/r2jt/vcgeneration/Utilities.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/treewalkers/NestedFuncWalker.java
When forming parsimonious vcs, we will need to consider all the expressions in the current assume expression before deciding if we can toss the given out. For example, we could have "Assume x = y and y = z" and "Confirm z = #x" as our goal. The old way would look at "x = y" and "y = z" separately and consider "y = z" to be the only one useful. However, "x = y" would become useful because now "y = z" could potentially be used. 
The modified form parsimonious vc method first attempts to do substitutions if possible. Then it takes the remaining assume expressions we have not substituted and forms all possible implies until either the list of remaining assumes is 0 or we simply can't form any more implies. When we reach that stage, we can safely discard any remaining givens in the list.
Note: …
=> Parsimonious vc fix

src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java
For both module and operation parameters, we need to add the parameter's type constraints as givens. If we don't there will be VCs that will be unprovable due to missing givens. In this pull request, we are adding the module parameter type constraints. The operation parameter type constraints are already in the VC generator.
Note that the constraints that come from module parameters apply to every sub-construct we have, but the constraints that come from operation parameters only apply to the current operation/procedure we are visiting.
=> Parameter Type Constraints

src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java
The rule does not say we need this, so I am taking that assume clause out. Let's hope this doesn't break anything.
=> Don't need variable constraints in correspondence rule

src/main/java/edu/clemson/cs/r2jt/processing/PostProcessor.java, src/main/java/edu/clemson/cs/r2jt/translation/JavaTranslator.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/FacilityFormalToActuals.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/Utilities.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/treewalkers/NestedFuncWalker.java
1) When building a jar, if the facility does not have a 'Main', it throws a SourceErrorException instead of a standard NoSuchMethodError exception.
2) Updated the replacement logic in certain places.
=> Compiler fixes

src/main/java/edu/clemson/cs/r2jt/vcgeneration/Utilities.java
The general problem is that an OldExp containing either an VarExp or a replaceable DotExp should be considered as a replaceable Exp. In the case of ```A = #A```, the evaluation should say that both sides can be substituted. However if you have ```G = #A(i)```, then only the left hand side can be substituted.
=> Fixes to OldExp substitution

src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/CongruenceClassProver.java, src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/Utilities.java, src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/VerificationConditionCongruenceClosureImpl.java, src/main/java/edu/clemson/cs/r2jt/rewriteprover/VC.java
Test file (will need binary minus defined your workpsace):
Facility Int_Do_Nothing_Exercise;
uses Integer_Ext_Theory;
-- The operation below is intentionally buggy.
Operation Main();
Procedure
Var I, J, K: Integer;
Read(I);
Read(J);
Remember;
Presume (I - 1 <= I);
Confirm (J < I) = (J + 1 <= I);
Confirm (J > I) = (I + 1 <= J);
Confirm I - J = I + (-J);
end Main;
end Int_Do_Nothing_Exercise;
=> Expression Trees in VCs and Theorems replaced with favored symbols.

src/main/java/edu/clemson/cs/r2jt/absyn/OldExp.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/Utilities.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java, src/main/java/edu/clemson/cs/r2jt/vcgeneration/treewalkers/NestedFuncWalker.java
Fixes when applying expression substitution. Expressions can only be substituted when it is an `EqualsExp` and exactly one of the sides is a `VarExp`. `OldExp` is not a `VarExp` and shouldn't be replaced. Also, changed some of the code to use `substitute` instead of `replace`.
=> VC Generator Fixes

.travis.yml, bin/runCompilerTests, bin/tests/filesToAnalyze.txt, bin/tests/filesToProve.txt, src/main/java/edu/clemson/cs/r2jt/Main.java
Using the RESOLVE jar generated by the continuous integration, we test it against files in the latest version of the RESOLVE work space. 
Note that we only check to see if the compilation terminates (i.e. No exceptions thrown). We do not check to see if the compiler produced the right results.
=> More Continuous Integration

bin/runCompilerTests, bin/tests/filesToBuildJar.txt, src/main/java/edu/clemson/cs/r2jt/translation/AbstractTranslator.java
#233 Changed the `FacilityOperationDec` object. Now it contains an `OperationDec` instead of individual elements. However, this change wasn't appropriately addressed in the Translator. This should fix this issue.
Also added continuous integration checks for creating jars.
=> Translator Fix

src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java
This fixes the issue where the type constraint for parameters with `alters`, `replaces` or `updates` modes weren't generated as a given for subsequent statements.
=> Fixes to Call Statement Rule

src/main/java/edu/clemson/cs/rsrg/init/CompileEnvironment.java, src/main/java/edu/clemson/cs/rsrg/init/Controller.java, src/main/java/edu/clemson/cs/rsrg/init/ResolveCompiler.java, src/main/java/edu/clemson/cs/rsrg/statushandling/StdErrHandler.java, src/main/java/edu/clemson/cs/rsrg/statushandling/SystemStdHandler.java, src/main/java/edu/clemson/cs/rsrg/statushandling/WriterStatusHandler.java
It probably is better if we output the information/warning and error to different writers.
=> Separate information/warning from error messages

src/main/java/edu/clemson/cs/rsrg/init/Controller.java
The `findDependencies` method is a recursive method that obtains dependent modules. However, there is a bug in the old code that we would call this method even if we have already encountered and compile this file. This will result in a ton of unnecessary recursive calls. The only time we need to call it recursively is when we encounter a new import that we haven't compiled.
=> Only find dependencies if it is new module

src/main/java/edu/clemson/cs/rsrg/init/CompileEnvironment.java, src/main/java/edu/clemson/cs/rsrg/init/Controller.java, src/main/java/edu/clemson/cs/rsrg/init/file/ResolveFile.java, src/main/java/edu/clemson/cs/rsrg/init/output/FileOutputListener.java, src/main/java/edu/clemson/cs/rsrg/init/pipeline/AbstractPipeline.java, src/main/java/edu/clemson/cs/rsrg/misc/Utilities.java, src/main/java/edu/clemson/cs/rsrg/treewalk/WalkerCodeGenerator.java, src/main/java/edu/clemson/cs/rsrg/typeandpopulate/utilities/HardCoded.java, test/java/edu/clemson/cs/rsrg/parsing/GrammarTest.java, test/java/edu/clemson/cs/rsrg/vcgeneration/sequents/SequentReductionTest.java
This pull request addresses the following issues:
1. `FileInputStream` and `FileOutputStream` is considered to be harmful. Followed the suggestions of this [blog post](https://www.cloudbees.com/blog/fileinputstream-fileoutputstream-considered-harmful) to fix it.
2. `AntlrInputStream` is deprecated. Changed everything to use `CharStream`, `CharStreams` and `UnbufferedCharStream`.
=> File Stream Update

.travis.yml, bin/runAnalyzeTests, bin/runBuildJarTests, bin/runProveTests
Right now, our compiler tests stage takes too long. We should run the tasks separately to speed up the integration tests.
=> Parallelize Compiler Tests

src/main/java/edu/clemson/cs/rsrg/typeandpopulate/Populator.java, src/main/java/edu/clemson/cs/rsrg/vcgeneration/VCGenerator.java, src/main/java/edu/clemson/cs/rsrg/vcgeneration/utilities/Utilities.java, src/main/java/edu/clemson/cs/rsrg/vcgeneration/utilities/treewalkers/UniqueSymbolNameExtractor.java
These changes are meant to improve (fix) the VC generator and deal with instantiating `Facility` types and substituting the instantiated formal parameters with its actual. It should be able to distinguish types based on module qualifiers and make intelligent choices when there isn't one (which usually means that there is only one type with that name).
=> VC Generator Symbol Matching Improvement

src/main/java/edu/clemson/cs/rsrg/absyn/expressions/mathexpr/FunctionExp.java, src/main/java/edu/clemson/cs/rsrg/absyn/expressions/mathexpr/MathExp.java, src/main/java/edu/clemson/cs/rsrg/vcgeneration/proofrules/statements/FacilityInitStmtRule.java, src/main/java/edu/clemson/cs/rsrg/vcgeneration/utilities/Utilities.java, src/main/java/edu/clemson/cs/rsrg/vcgeneration/utilities/VerificationContext.java
1. Copy qualifier and quantifiers for `FunctionExp` wherever possible.
2. Substitute concept formal parameters with actual arguments when obtaining the facility initialization ensures clause.
=> VC Generation Fixes

src/main/java/edu/clemson/cs/r2jt/archiving/Archiver.java
Don't print debug messages to console when using the compiler within the WebIDE
=> Archiver - No Debug Messages

src/main/java/edu/clemson/cs/rsrg/vcgeneration/utilities/Utilities.java
Rather than producing `x /= y` when negating the expression `x = y`, we now produce `not(x = y)`. The reason we do this is so that the sequent reduction rules can take care of it.
=> Replace Not Equals with Negation Expression

src/java/edu/clemson/rsrg/vcgeneration/proofrules/statements/AssumeStmtRule.java
Passed along the location details when we do the assume substitution step.
=> Fixed Missing Locaiton Detail when Substituting

src/java/edu/clemson/rsrg/nProver/utilities/treewakers/AbstractRegisterSequent.java, src/java/edu/clemson/rsrg/vcgeneration/proofrules/declarations/AbstractBlockDeclRule.java, src/java/edu/clemson/rsrg/vcgeneration/proofrules/declarations/operationdecl/ProcedureDeclRule.java
Redefined the walk for `DotExp` so we can handle those kinds of expressions. Also fixed issues where the argument cache map in our treewalker won't store expressions with the same name/value, but it isn't the same expression.
=> Added to code to handle DotExp

src/java/edu/clemson/rsrg/typeandpopulate/query/searchpath/UnqualifiedPath.java
When doing a multisearch query, we need to search the imports (if named) and not the imports of our imports.
=> No recursive search of named imports

src/java/edu/clemson/rsrg/typeandpopulate/Populator.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/FacilityEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/MathSymbolEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/OperationEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/OperationProfileEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/ProcedureEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/ProgramParameterEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/ProgramTypeEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/ProgramVariableEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/ShortFacilityEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/SymbolTableEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/TheoremEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/TypeFamilyEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/entry/TypeRepresentationEntry.java, src/java/edu/clemson/rsrg/typeandpopulate/symboltables/ScopeBuilder.java
As we populate the symbol table, we store the operators in each of the mathematical assertions we encounter. This will allow the prover to retrieve this information quickly without having to re-walk the expression.
=> Extract Theorem Operators
