ClemsonRSRG/RESOLVE

src/main/java/edu/clemson/cs/r2jt/absynnew/ImportBlockAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/ModuleAST.java

Ran the formatter on two of the files.

formatting

---

pom.xml
src/main/java/edu/clemson/cs/r2jt/absynnew/AbstractNodeBuilder.java
src/main/java/edu/clemson/cs/r2jt/absynnew/ImportBlockAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/MathTypeAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/ModuleBlockAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/NamedTypeAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/ResolveAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/ResolveParserFactory.java
src/main/java/edu/clemson/cs/r2jt/absynnew/TreeBuildingVisitor.java
src/main/java/edu/clemson/cs/r2jt/absynnew/TreeUtil.java
src/main/java/edu/clemson/cs/r2jt/absynnew/TreeWalkerVisitor.java
src/main/java/edu/clemson/cs/r2jt/absynnew/TypeAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/WalkerCodeGenerator.java
src/main/java/edu/clemson/cs/r2jt/absynnew/decl/DeclAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/decl/MathDefinitionAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/decl/ModuleParameterAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/decl/OperationAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/decl/OperationImplAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/decl/OperationSigAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/decl/TypeModelAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/decl/TypeParameterAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/decl/VariableAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/expr/MathTupleAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/expr/ProgNameRefAST.java
src/main/java/edu/clemson/cs/r2jt/absynnew/expr/ProgOperationRefAST.java

I hope to make this the last documentation/maintenance update to the new absyn additions. It shouldn't be too painful as those are the only files changed (the new ones).

Absyn (final?) additions

---

src/main/java/edu/clemson/cs/r2jt/absyn/AssumeStmt.java
src/main/java/edu/clemson/cs/r2jt/absyn/ConfirmStmt.java
src/main/java/edu/clemson/cs/r2jt/init/Controller.java
src/main/java/edu/clemson/cs/r2jt/init/FileLocator.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/AssertiveCode.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/Utilities.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java

This build generates performance vcs if possible. Below is a summary of all the changes
1. Introduced a flag "PVCs" that will generate performance vcs. This flag will require the new vc generator flag to be set.
2. Added the following rules for: procedure/function declaration, variable declaration, if/else statement, while statement, assume statement, confirm statement, call/function call statement and swap statement.
3. Deleted unnecessary constraint givens generated by the variable declaration rule.

Vc performance

---

src/main/java/edu/clemson/cs/r2jt/typeandpopulate/Populator.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration2/VCGenerator.java

This is a simple pull request that does the following:
1) Formatted a file that was left unformatted.
2) Created a new package for the new VC Generator. This new VC Generator will use the ANTLR4 structure that is going to be the new standard.

New VCGenerator

---

pom.xml
src/main/java/edu/clemson/cs/r2jt/Main.java
src/main/java/edu/clemson/cs/r2jt/typeandpopulate/Populator.java
src/main/java/edu/clemson/cs/r2jt/typeandpopulate2/PopulatingVisitor.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/AssertiveCode.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java

Lots of fixes for the VC Generator

Vc gen fixes

---

src/main/java/edu/clemson/cs/r2jt/vcgeneration/Utilities.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java

1) Don't replace expressions involving P_val (or a variation of P_val)
2) Z won't exist as a type I can directly get from the TypeGraph, so the VC Generator now queries for it.

More vc gen fix

---

src/main/java/edu/clemson/cs/r2jt/misc/HardCoded.java
src/main/java/edu/clemson/cs/r2jt/misc/HardCoded2.java

Added Blair's changes back in.

No hardcoded z

---

src/main/java/edu/clemson/cs/r2jt/vcgeneration/FacilityFormalToActuals.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/Utilities.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/treewalkers/NestedFuncWalker.java

As of right now, the rule is still incomplete. However all the replacements for concept arguments should be replaced appropriately for all instantiated facilities.

Changes to the Facility_Decl_Rule

---

src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/CongruenceClassProver.java
src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/ConjunctionOfNormalizedAtomicExpressions.java
src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/Registry.java
src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/TheoremCongruenceClosureImpl.java
src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/VerificationConditionCongruenceClosureImpl.java
src/main/java/edu/clemson/cs/r2jt/rewriteprover/VC.java

There was an error with the previous build. This one should fix the problem.

Formatted files and removed unused imports

---

src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/ConjunctionOfNormalizedAtomicExpressions.java
src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/Registry.java

Really big improvement in mid to large proofs.

Caching results of isSubtypeOf in Registry.

---

src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/ConjunctionOfNormalizedAtomicExpressions.java
src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/Registry.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/FacilityFormalToActuals.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/Utilities.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/treewalkers/NestedFuncWalker.java

1) Fixes an error when there are more than 1 facility in the file.
2) Throws an error if we didn't find a facility that instantiates that type.
3) Complete facility declaration rule.

Facility decl rule

---

src/main/java/edu/clemson/cs/r2jt/translation/AbstractTranslator.java
src/main/java/edu/clemson/cs/r2jt/translation/JavaTranslator.java
src/main/resources/templates/Java.stg

fixes for cpsc372, corrects an issue with the `jones_facility` passed around via email; fixes for translation of facility decls with n > 2 enhancements still pending.

translator fix

---

src/main/antlr3/edu/clemson/cs/r2jt/parsing/RLexer.g
src/main/java/edu/clemson/cs/r2jt/misc/HardCoded.java

1) Introduced the ability to write cls_intersection and cls_union.
2) Changed the built in union and intersection bindings to cls_intersection and cls_union.

Set Changes

---

src/main/antlr3/edu/clemson/cs/r2jt/parsing/RBuilder.g
src/main/antlr3/edu/clemson/cs/r2jt/parsing/RLexer.g
src/main/antlr3/edu/clemson/cs/r2jt/parsing/RParser.g
src/main/java/edu/clemson/cs/r2jt/absyn/PressumeStmt.java
src/main/java/edu/clemson/cs/r2jt/absyn/PresumeStmt.java
src/main/java/edu/clemson/cs/r2jt/absyn/ResolveConceptualVisitor.java
src/main/java/edu/clemson/cs/r2jt/treewalk/TreeWalkerVisitor.java
src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java

Presume Statements

---

src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/ConjunctionOfNormalizedAtomicExpressions.java
src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/Utilities.java
src/main/java/edu/clemson/cs/r2jt/congruenceclassprover/VerificationConditionCongruenceClosureImpl.java

Reverts ClemsonRSRG/RESOLVE#235

Revert ""Not" operator replacement for VC's and Theorems passed to the prover."

---

src/main/java/edu/clemson/cs/r2jt/vcgeneration/VCGenerator.java

Fixed a small error where functions inside if/loop conditions where not appropriately replacing facility formals with actuals.

VC Generator Fix

---

src/main/java/edu/clemson/cs/rsrg/typeandpopulate/FunctionApplicationFactory.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTAbstract.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTBigUnion.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTCartesian.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTFunction.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTFunctionApplication.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTGeneric.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTIntersect.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTNamed.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTPowertypeApplication.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTProper.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTSetRestriction.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTType.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTUnion.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typereasoning/TypeGraph.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/BindingVisitor.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/TypeVisitor.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/VariableReplacingVisitor.java

This pull request addresses part of the checklist in #250 and contains all the `MTTypes`. For now the global defined types in the `TypeGraph` are incomplete.

MTType Hierarchy Refactor

---

src/main/java/edu/clemson/cs/rsrg/typeandpopulate/entry/ProgramTypeDefinitionEntry.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/entry/SymbolTableEntry.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/programtypes/PTElement.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/programtypes/PTFacilityRepresentation.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/programtypes/PTFamily.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/programtypes/PTGeneric.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/programtypes/PTInstantiated.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/programtypes/PTNamed.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/programtypes/PTRecord.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/programtypes/PTRepresentation.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/programtypes/PTType.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/programtypes/PTVoid.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typereasoning/TypeGraph.java

This pull request addresses part of the checklist in #250 and contains all the `PTTypes`. For now all the symbol table entries are incomplete.

PTType Hierarchy Refactor

---

src/main/java/edu/clemson/cs/rsrg/misc/RCollections.java
src/main/java/edu/clemson/cs/rsrg/misc/Utilities.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/entry/FacilityEntry.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/exception/NoneProvidedException.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/InstantiatedScope.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/ModuleScope.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/utilities/ModuleParameterization.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/utilities/SpecRealizationPairing.java

#257 forgot to refactor `FacilityEntry`.

FacilityEntry Refactor

---

src/main/antlr3/edu/clemson/cs/r2jt/parsing/RBuilder.g
src/main/antlr3/edu/clemson/cs/r2jt/parsing/RLexer.g
src/main/antlr3/edu/clemson/cs/r2jt/parsing/RParser.g
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/query/GenericQuery.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/query/UnqualifiedNameQuery.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/query/searchpath/PossiblyQualifiedPath.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/query/searchpath/QualifiedPath.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/query/searchpath/UnqualifiedPath.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/MathSymbolTable.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/SyntacticScope.java

This pull request addresses part of the checklist in #250 and contains all the symbol table `Search Path`.

Search Path Refactor

---

src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTType.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/FinalizedScope.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typereasoning/TypeGraph.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/AlphaEquivalencyChecker.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/BindingVisitor.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/BoundVariableVisitor.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/CanonicalizingVisitor.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/ContainsNamedTypeChecker.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/MutatingVisitor.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/SymmetricBoundVariableVisitor.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/SymmetricVisitor.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/SyntacticSubtypeChecker.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/UnboundTypeAccumulator.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typevisitor/VariableReplacingVisitor.java

This pull request addresses part of the checklist in #250 and contains the different visitors for `MTTypes`.

Typevisitor Refactor

---

src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/BaseSymbolTable.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/InstantiatedSymbolTable.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/SymbolTable.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/utilities/LazyMappingIterator.java

This pull request addresses part of the checklist in #250 and contains the different visitors for `SymbolTables`.

Symbol Table Refactor

---

src/main/java/edu/clemson/cs/rsrg/typeandpopulate/entry/FacilityTypeRepresentationEntry.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/entry/TypeFamilyEntry.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/entry/TypeRepresentationEntry.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/exception/NoSuchModuleException.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/exception/NoSuchScopeException.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/MathSymbolTable.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/MathSymbolTableBuilder.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/ModuleScope.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/ModuleScopeBuilder.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/ScopeBuilder.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/ScopeRepository.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/symboltables/SyntacticScope.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typereasoning/TypeGraph.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/utilities/HardCoded.java

This pull request addresses part of the checklist in #250 and contains the different visitors for `ScopeRepositories`.

Scope Repository Refactor

---

src/main/java/edu/clemson/cs/rsrg/absyn/expressions/mathexpr/MathExp.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/Populator.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/mathtypes/MTType.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/typereasoning/TypeGraph.java

This pull request addresses part of the checklist in #250 and contains the new `TypeGraph`.

TypeGraph Refactor

---

src/main/java/edu/clemson/cs/rsrg/init/Controller.java
src/main/java/edu/clemson/cs/rsrg/init/ResolveCompiler.java
src/main/java/edu/clemson/cs/rsrg/init/pipeline/ASTOutputPipeline.java
src/main/java/edu/clemson/cs/rsrg/init/pipeline/AnalysisPipeline.java
src/main/java/edu/clemson/cs/rsrg/init/pipeline/VCGenPipeline.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/Populator.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/VCGenerator.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/absyn/statements/ChangeStmt.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/vcs/AssertiveCodeBlock.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/vcs/Sequent.java

This pull request addresses part of the checklist in #278 and contains the new `Sequent` class.

Assertive Code Blocks and Sequents

---

src/main/java/edu/clemson/cs/rsrg/astoutput/GenerateGraphvizModel.java
src/main/java/edu/clemson/cs/rsrg/init/pipeline/ASTOutputPipeline.java
src/main/java/edu/clemson/cs/rsrg/init/pipeline/AbstractPipeline.java
src/main/java/edu/clemson/cs/rsrg/init/pipeline/VCGenPipeline.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/Populator.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/VCGenerator.java
src/resources/templates/VCGenOutput.stg

Created a `StringTemplate 4` model for adding `VC` and `VC` generation details. This pull request addresses part of output handling in #278.

String Template for VC Generator

---

src/main/java/edu/clemson/cs/rsrg/typeandpopulate/Populator.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/sanitychecking/ValidFunctionCallChecker.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/sanitychecking/ValidOperationDeclChecker.java

This pull request addresses part of the checklist in #251 and addresses the issues #213 and #245.

Sanity Check Preserves and Evaluates Modes

---

src/main/java/edu/clemson/cs/rsrg/vcgeneration/VCGenerator.java

This pull request addresses part of the checklist in #278. It contains the complete `Which_Entails` declaration rule.

Which_Entails Declaration Rule

---

bin/runAnalyzeTests
bin/runBuildJarTests
bin/runProveTests
pom.xml
src/main/java/edu/clemson/cs/rsrg/init/ResolveCompiler.java

Update compiler version to `Fall 2017` and upgraded most of the plugins to their latest stable version.

General Updates

---

pom.xml

Update the plugins to the latest version provided by `Antlr`

Update Antlr to 4.7.1

---

src/main/java/edu/clemson/cs/rsrg/vcgeneration/proofrules/declaration/FacilityDeclRule.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/proofrules/declaration/ProcedureDeclRule.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/proofrules/statement/CallStmtRule.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/proofrules/statement/FuncAssignStmtRule.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/proofrules/statement/IfStmtRule.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/utilities/VerificationCondition.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/utilities/treewalkers/ProgramFunctionExpWalker.java

Also includes fixes for various different proof rules.

VCs for Recursive Operations

---

src/main/java/edu/clemson/cs/rsrg/init/ResolveCompiler.java
src/main/java/edu/clemson/cs/rsrg/init/flag/FlagDependencies.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/VCGenerator.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/utilities/Utilities.java
src/resources/templates/VCGenOutput.stg

**Improvements:**
1. Added a flag to turn on variable constraints.
**Fixes:**
1. Various different output display and template changes.
2. `null` pointer fix

Improvements and Fixes to VC Generator

---

src/main/java/edu/clemson/cs/rsrg/parsing/TreeBuildingListener.java
src/main/java/edu/clemson/cs/rsrg/parsing/sanitychecking/ValidSharedStateChecker.java
src/main/java/edu/clemson/cs/rsrg/parsing/sanitychecking/ValidTypeFamilyChecker.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/Populator.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/entry/OperationEntry.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/sanitychecking/ValidTypeFamilyChecker.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/proofrules/declaration/FacilityDeclRule.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/proofrules/statement/CallStmtRule.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/utilities/treewalkers/AtomicFormulaChecker.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/utilities/treewalkers/ProgramFunctionExpWalker.java

- Added two sanity checks for checking that the `Shared Variables` and `Type Family` assertion clauses are valid.
- Fixes for random crashes.

More Fixes for VSTTE

---

.travis.yml

1. Cache maven folder
2. Added a prepare cache stage to warm up the cache.

TravisCI Improvements

---

src/main/antlr4/edu/clemson/cs/rsrg/parsing/ResolveLexer.g4
src/main/antlr4/edu/clemson/cs/rsrg/parsing/ResolveParser.g4
src/main/java/edu/clemson/cs/rsrg/absyn/clauses/AssertionClause.java
src/main/java/edu/clemson/cs/rsrg/parsing/TreeBuildingListener.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/Populator.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/VCGenerator.java

Introduced `independent`/`dependent` type `correspondence` and added sanity checks throughout the compiler

Independent/Dependent Type Correspondence

---

src/main/java/edu/clemson/cs/rsrg/prover/output/Metrics.java

This pull request addresses part of the checklist in #316 and contains the `Metrics` class.

Metrics Refactor

---

src/main/java/edu/clemson/cs/rsrg/translation/AbstractTranslator.java
src/main/java/edu/clemson/cs/rsrg/translation/targets/CTranslator.java
src/main/java/edu/clemson/cs/rsrg/typeandpopulate/Populator.java

This pull request addresses part of the checklist in #321 and contains the tree walking methods in `AbstractTranslator` and in `CTranslator`. Note that this haven't been fully tested so some of the translation might not work!

Translation Refactor (Part 2)

---

.travis.yml

Update TravisCI sudo settings

---

bin/runAnalyzeTests
bin/runBuildJarTests
bin/runProveTests
pom.xml

Updated the various different plugins

Pom Updates

---

src/main/java/edu/clemson/cs/rsrg/vcgeneration/VCGenerator.java
src/main/java/edu/clemson/cs/rsrg/vcgeneration/proofrules/statements/CallStmtRule.java
src/resources/templates/VCGenOutput.stg

1. Eliminated blank lines for readability.
2. Minor re-wordings.

VC File Output Improvements

---

src/java/edu/clemson/rsrg/nProver/utilities/treewakers/AbstractRegisterSequent.java
src/java/edu/clemson/rsrg/nProver/utilities/treewakers/RegisterAntecedent.java
src/java/edu/clemson/rsrg/nProver/utilities/treewakers/RegisterSuccedent.java

Adding the capability for registering `PrefixExp` and `FunctionExp`.

Added to code to handle FunctionExp and PrefixExp

---

src/java/edu/clemson/rsrg/nProver/utilities/treewakers/AbstractRegisterSequent.java
src/java/edu/clemson/rsrg/nProver/utilities/treewakers/RegisterAntecedent.java
src/java/edu/clemson/rsrg/nProver/utilities/treewakers/RegisterSuccedent.java

Redefined the walk for `SetCollectionExp` so we can handle those kinds of expressions.

Added to code to handle SetCollectionExp

---

src/java/edu/clemson/rsrg/nProver/utilities/treewakers/AbstractRegisterSequent.java
src/java/edu/clemson/rsrg/nProver/utilities/treewakers/RegisterAntecedent.java
src/java/edu/clemson/rsrg/nProver/utilities/treewakers/RegisterSuccedent.java

Redefined the walk for `TupleExp` so we can handle those kinds of expressions.

Added to code to handle TupleExp

---

.github/workflows/maven.yml
README.md

Updated GitHub Actions to v3 and moved from AdoptJDK to Eclipse Temurin

GitHub Actions Updates
